import type { HomeEnv } from "./env";
import { handleSmartHome } from "./google";
import { bearer, constantTimeEqual, readForm } from "./security";
export { HomePcObject } from "./homepc-object";

const json = (value: unknown, status = 200): Response => Response.json(value, { status, headers: { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } });
const html = (value: string, status = 200): Response => new Response(value, { status, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store", "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; form-action 'self' https://oauth-redirect.googleusercontent.com; base-uri 'none'; frame-ancestors 'none'" } });

function oauthError(error: string, status = 400): Response { return json({ error }, status); }

function formPage(values: Record<string, string>): string {
  const esc = (v: string) => v.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
  const hidden = Object.entries(values).map(([key, value]) => `<input type="hidden" name="${esc(key)}" value="${esc(value)}">`).join("");
  return `<!doctype html><meta name="viewport" content="width=device-width"><title>Link HomePC</title><style>body{font:16px system-ui;background:#111827;color:#f9fafb;margin:0;padding:2rem}main{max-width:28rem;margin:auto;background:#1f2937;padding:2rem;border-radius:1rem}input,button{box-sizing:border-box;width:100%;padding:.9rem;margin:.5rem 0;border-radius:.5rem;border:1px solid #4b5563}button{background:#3b82f6;color:white;font-weight:700;border:0}</style><main><h1>Link HomePC</h1><p>Enter the private link password generated by bootstrap.</p><form method="post">${hidden}<label>Link password<input name="password" type="password" required autocomplete="current-password"></label><button>Link HomePC</button></form></main>`;
}

async function route(request: Request, env: HomeEnv): Promise<Response> {
  const url = new URL(request.url);
  const home = env.HOMEPC.getByName("private-homepc-account");
  if (url.pathname === "/" && request.method === "GET") return html("<!doctype html><title>HomePC</title><h1>HomePC cloud is running</h1><p>No credentials are displayed here.</p>");
  if (url.pathname === "/health" && request.method === "GET") return json({ ok: true, service: "homepc-cloud", time: new Date().toISOString() });
  if (url.pathname === "/device/ws" && request.method === "GET") return home.fetch(request);
  if (url.pathname === "/oauth/authorize" && request.method === "GET") {
    const clientId = url.searchParams.get("client_id") ?? "";
    const redirectUri = url.searchParams.get("redirect_uri") ?? "";
    const responseType = url.searchParams.get("response_type") ?? "";
    const state = url.searchParams.get("state") ?? "";
    if (!await constantTimeEqual(clientId, env.GOOGLE_CLIENT_ID)) return oauthError("invalid_client", 401);
    if (redirectUri !== env.GOOGLE_REDIRECT_URI || responseType !== "code" || !state) return oauthError("invalid_request");
    return html(formPage({ client_id: clientId, redirect_uri: redirectUri, response_type: responseType, state }));
  }
  if (url.pathname === "/oauth/authorize" && request.method === "POST") {
    const form = await readForm(request);
    const clientId = form.get("client_id") ?? "";
    const redirectUri = form.get("redirect_uri") ?? "";
    const responseType = form.get("response_type") ?? "";
    const state = form.get("state") ?? "";
    if (!await constantTimeEqual(clientId, env.GOOGLE_CLIENT_ID)) return oauthError("invalid_client", 401);
    if (redirectUri !== env.GOOGLE_REDIRECT_URI) return oauthError("redirect_uri_mismatch");
    if (responseType !== "code") return oauthError("unsupported_response_type");
    if (!state) return oauthError("missing_state");
    const safeValues = { client_id: clientId, redirect_uri: redirectUri, response_type: "code", state };
    if (!await constantTimeEqual(form.get("password") ?? "", env.LINK_PASSWORD)) return html(formPage(safeValues) + "<p>Incorrect password.</p>", 401);
    // `state` is an opaque value generated and validated by Google (the OAuth
    // client). Preserve it exactly, but do not make mobile retries depend on
    // server-side state that may have expired or already been consumed.
    const code = await home.authorizeCode(env.GOOGLE_REDIRECT_URI, Number(env.AUTH_CODE_TTL_SECONDS));
    const redirect = new URL(env.GOOGLE_REDIRECT_URI); redirect.searchParams.set("code", code); redirect.searchParams.set("state", state);
    // A 303 guarantees that Android's embedded browser follows the callback
    // with GET instead of attempting to repeat the password form POST.
    return Response.redirect(redirect.toString(), 303);
  }
  if (url.pathname === "/oauth/token" && request.method === "POST") {
    const form = await readForm(request);
    const basic = request.headers.get("Authorization");
    let clientId = form.get("client_id") ?? ""; let clientSecret = form.get("client_secret") ?? "";
    if (basic?.startsWith("Basic ")) { try { [clientId, clientSecret] = atob(basic.slice(6)).split(":", 2) as [string, string]; } catch { return oauthError("invalid_client", 401); } }
    if (!await constantTimeEqual(clientId, env.GOOGLE_CLIENT_ID) || !await constantTimeEqual(clientSecret, env.GOOGLE_CLIENT_SECRET)) return oauthError("invalid_client", 401);
    const ttl = Number(env.ACCESS_TOKEN_TTL_SECONDS);
    if (form.get("grant_type") === "authorization_code") {
      if (form.get("redirect_uri") !== env.GOOGLE_REDIRECT_URI) return oauthError("invalid_grant");
      const result = await home.exchangeCode(form.get("code") ?? "", env.GOOGLE_REDIRECT_URI, ttl);
      return result ? json({ token_type: "Bearer", access_token: result.accessToken, refresh_token: result.refreshToken, expires_in: ttl }) : oauthError("invalid_grant");
    }
    if (form.get("grant_type") === "refresh_token") {
      const accessToken = await home.refresh(form.get("refresh_token") ?? "", ttl);
      return accessToken ? json({ token_type: "Bearer", access_token: accessToken, expires_in: ttl }) : oauthError("invalid_grant");
    }
    return oauthError("unsupported_grant_type");
  }
  if (url.pathname === "/smarthome" && request.method === "POST") {
    const token = bearer(request); if (!token) return oauthError("unauthorized", 401);
    const length = Number(request.headers.get("content-length") ?? "0"); if (length > 65_536) return oauthError("request_too_large", 413);
    const body: unknown = await request.json();
    const result = await handleSmartHome(body, token, home, Number(env.COMMAND_TIMEOUT_MS));
    return "error" in result && result.error === "unauthorized" ? oauthError("unauthorized", 401) : json(result);
  }
  if (url.pathname === "/admin/status" && request.method === "GET") {
    const token = bearer(request) ?? ""; if (!await constantTimeEqual(token, env.ADMIN_TOKEN)) return oauthError("unauthorized", 401);
    return json({ linked: await home.linked(), agent: await home.status(), reportState: await home.willReportState(), routines: await home.routines(), audit: await home.recentAudit() });
  }
  return json({ error: "not_found" }, 404);
}

export default {
  async fetch(request: Request, env: HomeEnv): Promise<Response> {
    try { return await route(request, env); }
    catch (error) {
      console.error(JSON.stringify({ message: "request_failed", path: new URL(request.url).pathname, error: error instanceof Error ? error.message : "unknown" }));
      return json({ error: "internal_error" }, 500);
    }
  },
} satisfies ExportedHandler<HomeEnv>;
