<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType><RuntimeIdentifier>win-x64</RuntimeIdentifier><SelfContained>false</SelfContained></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HomePC.Core\HomePC.Core.csproj" />
    <ProjectReference Include="..\HomePC.Windows\HomePC.Windows.csproj" />
  </ItemGroup>
</Project>

